Add more `Event`
petabi/review-database pull request #103
Opened 2023-06-23 00:54 UTC by BLYKIM

- Added more event objects with `conn`, `ftp`, `http`, `ldap`
- Fixed `Event::count_network`.

각 이벤트의 Match trait에 대해 임의로 넣은 값들이 있어 확인 부탁드립니다.

2023-06-23 02:14 UTC, msk commented on src/event.rs
> +const MULTI_HOSTS_PORT_SCAN: &str = "Multi Hosts Port Scan";
hosts -> host

2023-06-23 02:14 UTC, msk commented on src/event.rs
> +    ///
Why are these comments empty?

2023-06-23 07:20 UTC, syncpark requested changes

2023-06-23 07:20 UTC, syncpark commented on src/event/conn.rs
> +        6
ExternalDDos는 UDP, TCP 둘 모두 탐지하지 않을까요? 
1. 여기서 6(tcp)를 사용하려면 Hog에서 ExternalDDos를 탐지할 때 TCP만을 대상으로 하던가 아니면 
2. ExternalDDosFields에 proto 필드를 추가하든가 해야합니다.

2023-06-23 07:20 UTC, syncpark commented on src/event/conn.rs
> +        "External DDos"
다른 탐지 이벤트에서는 모두 소문자를 사용했는데 여기는 대문자들이 포함되어 있습니다. 통일!!이 필요합니다.

2023-06-23 07:20 UTC, syncpark commented on src/event/conn.rs
> +        6
MultiHostPortScan도 UDP, TCP 모두 탐지 가능한지 않나요? proto 값을 6으로 고정하려면 Hog의 탐지 알고리즘이 TCP 이벤트만을 대상으로 동작하든가 아니면 proto 필드를 추가해주세요.

2023-06-26 07:09 UTC, syncpark approved these changes

2023-06-26 21:27 UTC, msk commented on CHANGELOG.md
> +- Fixed `Event::TorConnection` and `Event::DomainGenerationAlgorithm` in
What is the problem that this PR fixes?

2023-06-26 23:53 UTC, BLYKIM commented on CHANGELOG.md
> +- Fixed `Event::TorConnection` and `Event::DomainGenerationAlgorithm` in
Code that was executed outside of if event.matches() has been moved inside the if statement, However if it is correct to execute it outside of the if statement, I will revise it again.

2023-06-27 00:14 UTC, msk commented on CHANGELOG.md
> +- Fixed `Event::TorConnection` and `Event::DomainGenerationAlgorithm` in
The following is my suggestion for this entry:

- Adjusted the counting routine for `TorConnection` and `DomainGenerationAlgorithm` events to address an issue of overcounting destination IP addresses. Previously, the counter was incremented for each destination address regardless of whether the event matched the specified `locator` and `filter`. The logic has been updated so that now both source and destination addresses are only considered if the event matches the `locator` and `filter`. This change corrects the count by ensuring only relevant events are considered in the total tally.

2023-06-27 00:45 UTC, msk approved these changes

2023-06-27 00:52 UTC, merged

2023-06-27 00:52 UTC, syncpark approved these changes