Enhance backup logic
petabi/review-database pull request #105
Opened 2023-06-23 06:49 UTC by kimhanbeom

- Added new module 'postgres' to support postgresql.
- Enhance `backup::list`/`backup::create`/`backup::restore`/`backup::recovery` function to support postgresql.
- Added `backup::purge_old_backups` for apply immediately after `num_backups_to_keep` is changed.

Closes: #71, #76, #80

2023-06-23 08:16 UTC, syncpark requested changes

2023-06-23 08:16 UTC, syncpark commented on src/backup/postgresql.rs
> +        return Err(anyhow!("fail to remove old database. {:?}", e));
fail to remove old database -> fail to `copy` database
copy or backup

2023-06-23 08:16 UTC, syncpark commented on src/backup/postgresql.rs
> +const DEFAULT_PATH_ENV: &str = "/usr/sbin:/usr/bin:/sbin:/bin";
DEFAULT_PATH_ENV는 docker, cp 등의 커맨드를 찾기 위한 기본 경로입니다.
만일 이들이 `/usr/bin` 아래에 모두 모여있다면 그리고 그게 현재 제품을 설치한 모든 고객서버에서 똑같은 상황이라면, 다른 경로는 필요가 없습니다.

현재 코드에서 사용하는 docker, cp는 `/usr/bin` 혹은 `/bin`에 설치됩니다. 나머지는 삭제하는게 좋겠습니다.
다만 만일의 경우를 대비하여 확실하게 에러 메시지를 저장하거나 커맨드가 해당 경로에 존재하는지 확인할 필요는 있겠습니다.

2023-06-27 09:03 UTC, kimhanbeom commented
해당 사항 수정 완료 했습니다.

2023-06-28 01:16 UTC, syncpark requested changes

2023-06-28 01:20 UTC, kimhanbeom commented on CHANGELOG.md
> +  existing backup `creat`/`list`/`restore`/`recover` function to also support
수정 완료 했습니다.

2023-06-28 07:19 UTC, syncpark approved these changes

2023-06-29 03:21 UTC, minshao commented on src/backup.rs
>      }
```Rust
     let res = {
         let store = store.read().await;
         store.get_backup_info()
     };
     let mut backup_list = match res {
         Ok(backup_list) => {
             info!("generate database backup list");
             backup_list
                 .into_iter()
                 .map(std::convert::Into::into)
                 .collect()
         }
         Err(e) => {
             warn!("failed to generate backup list: {:?}", e);
             return Err(e);
         }
    }
    if let Err(e) = postgres_backup_list(backup_path, &mut backup_list) {
         return Err(anyhow!(
             "failed to add list information from a relational database: {e:?}"
         ));
    }

    

```
Read lock should be released as soon as possible. i.e. Add the `postgres_backup_list` call after the lock has been released

2023-06-29 03:22 UTC, msk requested changes

2023-06-29 03:22 UTC, msk commented on src/backup/postgresql.rs
> +    run_command("docker", None, &args)
The current implementation assumes the presence of Docker, which may not be universally available or preferred in all deployment scenarios. For maximum flexibility, the `review-database` should be able to support various methods of running `pg_dump` and shouldn't rely on Docker or any specific containerization technology.

Therefore, we recommend making this more flexible by allowing the user to provide the full path to the `pg_dump` command at runtime. This could be achieved through a configuration setting or a command-line argument, for example. By using the full path, `review-database` doesn't need to manage or modify the `PATH` environment variable itself, which makes it more resilient to differences in system configuration and more reliable in terms of finding the correct `pg_dump` command.

The command could be something like `/usr/bin/pg_dump` or `/usr/local/bin/docker exec -i [container] pg_dump`, depending on the user's specific setup.

This would allow for greater flexibility and accommodate a wider range of deployment scenarios.

2023-06-29 03:22 UTC, msk commented on src/backup/postgresql.rs
> +    let dump_file = format!("{DEFAULT_POSTGRES_TEMP_DIR}/{DEFAULT_POSTGRES_DUMP_FILE}");
`DEFAULT_POSTGRES_TEMP_DIR` is being used to construct the path for the database dump file. While this works, it may not be the best approach because it assumes a particular directory structure and relies on hardcoded paths.

Instead, I recommend using the `tempfile` crate, which is a library designed for dealing with temporary files in Rust. This crate creates files and directories in the location returned by `std::env::temp_dir()`, which respects the operating system's conventions and is generally a good place to store temporary files.

2023-06-29 03:22 UTC, msk commented on src/backup/postgresql.rs
> +    if !Path::new(DEFAULT_HOST_TEMP_DIR).exists() && fs::create_dir(DEFAULT_HOST_TEMP_DIR).is_err()
As `review-database` should not make assumptions about the environment where `REview` is running, this default directory path may not always be applicable or suitable. It could lead to issues on different operating systems or environments where the path is not accessible or does not exist.

Therefore, I suggest altering the implementation to receive this temporary directory path as an argument from `REview`. This would make the feature more flexible and adaptable to different environments, as `REview` would have more knowledge of the suitable paths in its running environment.

2023-06-29 03:32 UTC, minshao commented on src/backup.rs
> +    if let Err(e) = store.restore_from_backup(backup_id) {
please drop `store` as soon as restore is completed

2023-06-29 03:32 UTC, minshao commented on src/backup.rs
> +    let recovery_id = match store.recover() {
please drop `store` as soon as `recover` is called

2023-06-29 04:20 UTC, kimhanbeom commented on src/backup/postgresql.rs
> +    let dump_file = format!("{DEFAULT_POSTGRES_TEMP_DIR}/{DEFAULT_POSTGRES_DUMP_FILE}");
`DEFAULT_POSTGRES_TEMP_DIR` means the tmp folder of the `container` in `Postgres`. Save the result of `pg_dump` to the tmp of the container, copy the saved dump file to the path provided by the host, and finally backup the copied file.

2023-06-29 22:52 UTC, minshao commented on src/backup.rs
> +            timestamp: Utc.timestamp_nanos(backup.timestamp * BACKUP_TIMESTAMP_CONV_UNIT),
using `Utc::from_timestamp_opt(backup.timestamp, 0).expect("some message")` would be a better choice IMHO.

2023-06-29 22:52 UTC, minshao commented on src/backup.rs
> +                let _res = create(&store, false, &backup_cfg);
The lock of `backup_cfg` will be hold while trying to get `store` lock. It's very likely to cause a deadlock.
A safer option is to pass `backup_cfg` to `create` function which will have 2 phases: 1. get the lock for `store` and backup rocksdb, release the lock; 2. get the lock for `backup_cfg` and backup for `postgres` and release the lock;

2023-06-29 22:52 UTC, minshao commented on src/backup.rs
> +    backup_cfg: &BackupConfig,
As mentioned earlier, switching to `&Arc<RwLock<BackupConfig>>`

2023-06-29 22:52 UTC, minshao commented on src/backup.rs
> +    cfg: &BackupConfig,
Similar to `create` function: use `cfg: &Arc<RwLock<BackupConfig>>` and separate the 2 restoring phases

2023-06-29 22:52 UTC, minshao commented on src/backup.rs
> +    backup_cfg: &BackupConfig,
Similar to create function: use cfg: &Arc<RwLock<BackupConfig>> and separate the 2 restoring phases

2023-06-29 22:52 UTC, minshao commented on src/backup.rs
> +pub async fn recover(store: &Arc<RwLock<Store>>, cfg: &BackupConfig) -> Result<u32> {
Similar to create function: use cfg: &Arc<RwLock<BackupConfig>> and separate the 2 restoring phases

2023-06-29 22:52 UTC, minshao commented on src/backup.rs
> +pub async fn list(store: &Arc<RwLock<Store>>, backup_path: &Path) -> Result<Vec<BackupInfo>> {
although I haven't seen the usage of the function yet, it's better to keep it inline with other places and pass the `&Arc<RwLock<BackupConfig>>` for a unified interface.

2023-06-30 01:54 UTC, kimhanbeom commented on src/backup.rs
> +                let _res = create(&store, false, &backup_cfg);
For `create` and `purge_old_backups`, rocksdb require `num_of_backups`, so eventually the lock on the `BackupConfig` will take until the end of the function.

So, what if I modified it like this?

```
   let backup_cfg = { 
            backup_cfg.read().await.clone() 
    };
```

Previously, passing a reference to a value using clone would still hold the lock, but this would release the lock immediately.

2023-06-30 03:31 UTC, minshao commented on src/backup.rs
> +                let _res = create(&store, false, &backup_cfg);
In short, I don't think that would do the trick. 

The reason for using lock is to guarantee that at, any given time, if someone is writing, no one else can read or write. By doing what you explained, a read while write might happen for the file listed under the directory of `backup_cfg`.

2023-07-05 23:21 UTC, minshao commented on src/backup.rs
> +                let _res = create(&store, false, &backup_cfg);
Let me know if there's anything I can help with~

2023-07-06 02:04 UTC, kimhanbeom commented
@minshao 
We are currently working on a simultaneous release to all repositories. We had a meeting with sehkone and decided not to include the improved backup in this release, So I'll change it to WIP until the next version is released.

2023-12-27 06:36 UTC, syncpark approved these changes

2023-12-27 06:36 UTC, syncpark commented
@kimhanbeom rebase 해주세요

2024-02-27 21:44 UTC, msk commented
Closed per discussion in #206.

2024-02-27 21:44 UTC, closed without merging