Add `CryptoCurrency` event & Remove `src_port` from `BruteForce` events.
petabi/review-database pull request #110
Opened 2023-07-03 07:02 UTC by BLYKIM

2023-07-03 22:27 UTC, msk requested changes

2023-07-03 22:27 UTC, msk commented on CHANGELOG.md
> +- Modify `LdapPlainText` fields.
This CHANGELOG entry could benefit from more detail. Given that the review-database crate is used by other projects, it's important to ensure that our CHANGELOG entries provide sufficient information for developers of those projects to understand what has been changed, why it has been changed, and how it might affect their usage of our crate.

For example, if there are breaking changes, we need to clearly state those so that dependent projects can plan their upgrades accordingly. Or if we've made performance improvements, developers may want to upgrade even if they don't need to for compatibility reasons.

A more informative CHANGELOG entry might look something like this:

- Modified the `LdapPlainText` fields to improve [functionality/security/performance/etc.]. Changes include [description of specific changes]. This change [will/will not] require updates in dependent projects due to [reason].

Would you be able to revise your CHANGELOG entry accordingly?

2023-07-05 16:27 UTC, msk requested changes

2023-07-05 16:27 UTC, msk commented on src/event.rs
> +    Cryptocurrency(Cryptocurrency),
While I understand the rationale behind the choice of this term, considering that the event is specifically triggered by identifying traffic to crypto mining pool sites, it might be more descriptive to name the event type "CryptocurrencyMiningPool".

This name suggests a more precise context for the event and provides greater clarity for those reviewing the database events in the future. By specifying that this event is associated with "mining pool" activities rather than a broader "cryptocurrency" context, we can better segment and analyze our data.

2023-07-06 01:45 UTC, syncpark approved these changes

2023-07-06 02:12 UTC, syncpark approved these changes

2023-07-06 04:31 UTC, closed without merging