Modify `BruteForce` fields
petabi/review-database pull request #116
Opened 2023-07-25 02:00 UTC by BLYKIM

[hog pr](https://github.com/aicers/hog/issues/486)

2023-07-25 04:18 UTC, syncpark requested changes

2023-07-25 04:18 UTC, syncpark commented on src/migration.rs
> +const COMPATIBLE_VERSION_REQ: &str = ">=0.12.0,<0.17.0-alpha";
RdpBruteforce, FtpBruteforce, ... 에 대한 Migration 기능이 필요

2023-07-26 03:57 UTC, syncpark requested changes

2023-07-26 03:57 UTC, syncpark commented on src/migration.rs
> +                    return Err(anyhow!("Failed to migrate events: Invalid Event value"));
에러 메시지 `Invalid Event value` -> `invalid event value`로 수정합시다.

2023-07-26 06:52 UTC, syncpark approved these changes

2023-07-27 05:54 UTC, syncpark commented
@BLYKIM Please rebase this branch.

2023-07-27 23:18 UTC, minshao approved these changes

2023-07-27 23:23 UTC, minshao approved these changes

2023-07-27 23:46 UTC, merged