Add BlockList
petabi/review-database pull request #119
Opened 2023-07-31 09:31 UTC by dayeon5470

2023-08-04 01:59 UTC, syncpark requested changes

2023-08-04 01:59 UTC, syncpark commented on src/event/conn.rs
> +            "{},{},{},{},{},Block List,3,{}",
Please change to read `Block List` static string from `BLOCK_LIST` const value in event.rs.

You don't need to care about other static string, because they will be modified in another branch now.

2023-08-04 01:59 UTC, syncpark commented on src/event/conn.rs
> +        EventCategory::CommandAndControl
Please change this EventCategory to `InitialAccess`

2023-08-10 00:50 UTC, syncpark approved these changes

2023-08-14 06:40 UTC, syncpark requested changes

2023-08-14 06:40 UTC, syncpark commented on src/event.rs
> +                            .entry(CRYPTOCURRENCY_MINING_POOL.to_string())
CRYPTOCURRENCY_MINING_POOL -> BlockList

2023-08-14 06:40 UTC, syncpark commented on src/event.rs
> +                            .entry(CRYPTOCURRENCY_MINING_POOL.to_string())
CRYPTOCURRENCY_MINING_POOL -> BLOCK_LIST ?

2023-08-14 08:08 UTC, syncpark approved these changes

2023-08-14 08:08 UTC, merged

2023-08-14 18:05 UTC, msk commented
@syncpark, I noticed that the version `0.17.0` was tagged using a regular tag. For better documentation and traceability, it's a good practice to use annotated tags when marking releases. Annotated tags store extra meta information, such as the tagger name, email, and date. It can be beneficial in the long run.

You might want to chat with @kimhanbeom, who can guide you on how to properly create annotated tags.