Add block list event to all protocols& Release 0.19.0
petabi/review-database pull request #137
Opened 2023-09-19 05:16 UTC by dayeon5470

Issue: https://github.com/petabi/review-database/issues/136

2023-09-19 19:04 UTC, minshao commented on CHANGELOG.md
> +- Added a 'blockList' event with `dcerpc`, `dns`, `http`, `kerberos`, `ldap`,
Might be better to replace "'blockList'" with "\`BlockList\`" for consistency.

2023-09-19 21:42 UTC, minshao commented on src/backends/postgres/de.rs
> +                    .map(|t| t.timestamp_nanos_opt().unwrap_or_default())
Please also update chrono version to 0.4.31 in Cargo.toml file

2023-09-20 00:45 UTC, syncpark commented
For cleaner commit log management, please move the Release 0.19.0 to the next PR.

2023-09-20 05:17 UTC, syncpark requested changes

2023-09-20 05:17 UTC, syncpark commented on src/event/dcerpc.rs
> +            "{},{},{},{},{},{} Text,3",
Please replace the `Text` to the protocol name `DceRpc` to distinguish events.
And other protocols too.

2023-09-20 05:17 UTC, syncpark commented on CHANGELOG.md
> +## [0.19.0] - 2023-09-19
Please move this Release to the next PR

2023-09-20 08:43 UTC, syncpark commented
@dayeon5470 
The `EventKind` in Hog and review-database has different element for `BlockList` events as follows.

You have to synchronize the `EventKind` enum definition.

```rust
// in Hog
pub enum EventKind {
    DnsCovertChannel,
    _HttpThreat,
    RdpBruteForce,
    RepeatedHttpSessions,
    Log,
    TorConnection,
    DomainGenerationAlgorithm,
    FtpBruteForce,
    FtpPlainText,
    PortScan,
    MultiHostPortScan,
    NonBrowser,
    LdapBruteForce,
    LdapPlainText,
    ExternalDdos,
    CryptocurrencyMiningPool,
    BlockList(RecordType),
}

// in review-database
pub enum EventKind {
    DnsCovertChannel,
    HttpThreat,
    RdpBruteForce,
    RepeatedHttpSessions,
    Log,
    TorConnection,
    DomainGenerationAlgorithm,
    FtpBruteForce,
    FtpPlainText,
    PortScan,
    MultiHostPortScan,
    NonBrowser,
    LdapBruteForce,
    LdapPlainText,
    ExternalDdos,
    CryptocurrencyMiningPool,
    BlockListConn,
    BlockListDns,
}
```

2023-09-22 06:10 UTC, syncpark commented
@dayeon5470 This PR should be merged with review-web. Please add these events to review-web too.

2023-09-25 00:57 UTC, syncpark approved these changes

2023-09-25 17:55 UTC, merged