Add `sensor`, `confidence`, and `learning_method` in `EventFilter`
petabi/review-database pull request #22
Opened 2023-04-20 23:33 UTC by sehkone

The eventList API requires the functionality to allow users to search for events based on sensor, confidence level, and learning method (either unsupervised or semi-supervised). Therefore, the ability to filter events using these parameters is included as a feature.

2023-04-21 04:16 UTC, sehkone commented
Since `cargo clippy` generates so many errors, I had to put the below in `lib.rs`.

`#![allow(clippy::missing_errors_doc)]`

2023-04-21 16:34 UTC, msk commented
> Since `cargo clippy` generates so many errors, I had to put the below in `lib.rs`.
> 
> `#![allow(clippy::missing_errors_doc)]`

We should avoid disabling clippy lints in the source codes. Please set this in your local clippy.toml instead.

2023-04-21 23:15 UTC, sehkone commented
> > Since `cargo clippy` generates so many errors, I had to put the below in `lib.rs`.
> > `#![allow(clippy::missing_errors_doc)]`
> 
> We should avoid disabling clippy lints in the source codes. Please set this in your local clippy.toml instead.

2023-04-21 23:15 UTC, sehkone commented
-

2023-04-22 00:09 UTC, msk requested changes

2023-04-22 00:09 UTC, msk commented on src/migration.rs
> +const DATABASE_VERSION_REQ: &str = ">=0.3.0,<0.5.0-alpha.5";
This is the version that doesn't need migration. Since this PR makes the previous version incompatible, this should be`"=0.5.0-alpha.5"`.

2023-04-22 00:09 UTC, msk commented on src/migration.rs
> +    let version_from = "0.4"; // this is the version that we'd like to migrate from
I don't think having these variables is a good idea. Eventually `migration` will contain many entries. In that case, what would `version_from` means? Each element in `migration` should have a different migrate-from version, and defining a variable only for one of them looks strange.

2023-04-22 00:09 UTC, msk commented on src/backends/postgres/de.rs
> +/// Deserializes an element of a `PostgreSQL` array.
This is wrong. Add (with git) clippy.toml to the top-level directory with the following content instead.

```toml
doc-valid-idents = [ "PostgreSQL" ]
```

2023-04-22 02:04 UTC, sehkone commented on src/migration.rs
> +    let version_from = "0.4"; // this is the version that we'd like to migrate from
I followed Min Shao's instructions without adapting them properly to this particular situation. However, I have now made adjustments to align with your intended outcome.

2023-04-22 02:05 UTC, sehkone commented on src/backends/postgres/de.rs
> +/// Deserializes an element of a `PostgreSQL` array.
I changed it back to the original version, without the quotation.

2023-04-22 02:06 UTC, sehkone commented on src/migration.rs
> +const DATABASE_VERSION_REQ: &str = ">=0.3.0,<0.5.0-alpha.5";
Now, I understand what it exactly means.

2023-04-22 02:30 UTC, msk commented on src/migration.rs
> +const DATABASE_VERSION_REQ: &str = ">=0.3.0,<0.5.0-alpha.5";
Sorry, I meant alpha.4, the version it becomes with this PR.

2023-04-22 02:31 UTC, msk commented on src/migration.rs
> +const DATABASE_VERSION_REQ: &str = ">=0.3.0,<0.5.0-alpha.5";
> Does this imply that it needs to be modified every time a new version emerges?

Only when the new version introduces a breaking change.

2023-04-22 02:40 UTC, sehkone commented on src/migration.rs
> +const DATABASE_VERSION_REQ: &str = ">=0.3.0,<0.5.0-alpha.5";
So, this means the minimum required version, doesn't it?

2023-04-22 02:40 UTC, sehkone commented on src/migration.rs
> +const DATABASE_VERSION_REQ: &str = ">=0.3.0,<0.5.0-alpha.5";
> Sorry, I meant alpha.4, the version it becomes with this PR.

Applied.

2023-04-22 20:23 UTC, msk commented on src/migration.rs
> +const DATABASE_VERSION_REQ: &str = ">=0.3.0,<0.5.0-alpha.5";
> So, this means the minimum required version, doesn't it?

I'm afraid the name is misleading. I need to change it to something else. It is the versions that use the exactly same database format as the current version.

2023-04-24 13:32 UTC, sehkone commented
@minshao assisted me in modifying the migration section, but I'm uncertain whether it meets @msk's requirements for `DATABASE_VERSION_REQ`. Would both of you review the changes and confirm that they are appropriate?

2023-04-24 17:13 UTC, msk commented on src/migration.rs
> +    if version >= break_version {
We cannot guarantee API compatibility with future versions. For example, 0.5.0-alpha.5 may introduce a change incompatible to 0.5.0-alpha.4. However, this condition will accept the database created by 0.5.0-alpha.5 and try to read it only to cause a potentially-disastrous error. Going back to an older version is common during debugging and thus we should prevent an old version from trying to read an incompatible future version's data.

2023-04-24 17:45 UTC, msk approved these changes

2023-04-24 17:46 UTC, merged