Modify `node::Settings` struct.
petabi/review-database pull request #290
Opened 2024-06-11 07:44 UTC by BLYKIM

- Remove `reconverge_giganto` fields from node struct `Settings`
- Remove the central server's address from node struct `Settings`
- Remove the `html` and redundant fields, add the vbs field
- Add migration code for `Node` struct

0.25 -> 0.26의 node 변경 migration 코드에 0.26ver의 node struct를 추가하였습니다.

Closes: #273
Closes: #280
Closes: #281
Closes: #287

2024-06-11 23:45 UTC, minshao commented on CHANGELOG.md
> +  - Removed `reconverge_giganto_[ip|port] fields.
Do you mean `reconverge_giganto_[ip|port]`?

2024-06-11 23:51 UTC, minshao requested changes

2024-06-11 23:51 UTC, minshao commented on CHANGELOG.md
> +- Modified the `NodeSettings` fields with migration code.
There's no need to mention `migration` in CHANGELOG. Only user visible change should be included. p.s. I'll handle the entries related to migration in *Added* section later.

2024-06-11 23:51 UTC, minshao commented on CHANGELOG.md
> +  - Merged `html` field to `txt` field.
The code doesn't show that `html` is merged into `txt` field. I think more explanation is needed here.

2024-06-12 01:54 UTC, BLYKIM commented on CHANGELOG.md
> +  - Removed `reconverge_giganto_[ip|port] fields.
thanks, done

2024-06-12 01:54 UTC, BLYKIM commented on CHANGELOG.md
> +- Modified the `NodeSettings` fields with migration code.
done

2024-06-12 02:05 UTC, BLYKIM commented on CHANGELOG.md
> +  - Merged `html` field to `txt` field.
done

2024-06-12 17:32 UTC, minshao requested changes

2024-06-12 17:32 UTC, minshao commented on CHANGELOG.md
> +  - Removed `html` field. and its boolean value has been merged into the
```suggestion
  - Removed `html` field, and its boolean value has been merged into the
```
Since `txt` is also a boolean, does that mean if `html` is considered a `txt`? i.e. In our system, are we categorizing `html` as `txt`? If so, to avoid any future confusion, please mention that in the CHANGELOG. Preferably, list all the file formats that are included in `txt`.

2024-06-12 17:32 UTC, minshao commented on src/tables/node.rs
> +    pub sensors: Option<Vec<String>>,
Now that it's a `Vec<_>`, should the database enforce an order to `sensors` and `protocols`? If so, please add a comment to each applicable variable and also mention it in the changelog.

2024-06-13 01:51 UTC, BLYKIM commented on CHANGELOG.md
> +  - Removed `html` field. and its boolean value has been merged into the
done

2024-06-13 01:51 UTC, BLYKIM commented on src/tables/node.rs
> +    pub sensors: Option<Vec<String>>,
done

2024-06-13 02:49 UTC, minshao requested changes

2024-06-13 02:49 UTC, minshao commented on CHANGELOG.md
> +    - The new protocols field should be sorted in alphabetical order.
Then in the corresponding migration code, the new protocols should be sorted.

2024-06-13 02:49 UTC, minshao commented on CHANGELOG.md
> +    - The new sensors field should also be sorted in alphabetical order.
Ditto

2024-06-13 02:57 UTC, BLYKIM commented on CHANGELOG.md
> +    - The new protocols field should be sorted in alphabetical order.
omg done

2024-06-13 02:57 UTC, BLYKIM commented on CHANGELOG.md
> +    - The new sensors field should also be sorted in alphabetical order.
done

2024-06-13 02:59 UTC, minshao requested changes

2024-06-13 02:59 UTC, minshao commented on CHANGELOG.md
> +  - Removed the redundant fields `html` and `txt` as they both represented the
Removed `html` field. Users who previously used `html` field to represent `MIME FileType::Text` should use `txt` field instead.

Since txt is not removed, the original log is a little bit confusing. The above is just for reference, feel free to adjust it.

2024-06-13 06:35 UTC, BLYKIM commented on CHANGELOG.md
> +  - Removed the redundant fields `html` and `txt` as they both represented the
done

2024-06-13 20:15 UTC, minshao approved these changes

2024-06-13 20:16 UTC, merged